'use strict';

// Test helpers shared by the workbook and browser-logic suites. Nothing here
// stubs the code under test: the handler is the real Vercel handler and the
// browser logic is the real inline script, both exercised end to end.

const fs = require('fs');
const os = require('os');
const path = require('path');
const vm = require('vm');
const ExcelJS = require('exceljs');

const ROOT = path.join(__dirname, '..');

// Captures what the handler sends back, including the raw workbook bytes.
const collectResponse = () => ({
  headers: {},
  statusCode: 0,
  body: null,
  buffer: null,
  setHeader(key, value) { this.headers[key] = value; return this; },
  status(code) { this.statusCode = code; return this; },
  json(payload) { this.body = payload; return this; },
  send(buffer) { this.buffer = buffer; return this; },
});

const callHandler = async (body, method = 'POST') => {
  const handler = require(path.join(ROOT, 'api/report/generate-workbook.js'));
  const res = collectResponse();
  await handler({ method, body }, res);
  return res;
};

// Re-reads the generated bytes from disk so the assertions run against a real
// .xlsx package rather than the in-memory objects that produced it.
const readGenerated = async (buffer) => {
  const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'sipgn-xlsx-')), 'out.xlsx');
  fs.writeFileSync(file, buffer);
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(file);
  return { workbook, file };
};

const cellValue = (sheet, address) => {
  const value = sheet.getCell(address).value;
  if (value && typeof value === 'object' && value.formula !== undefined) return `=${value.formula}`;
  if (value && typeof value === 'object' && value.result !== undefined) return value.result;
  return value;
};

// Loads the part of index.html's inline script that holds the book logic and
// exposes the functions under test. Everything above the LAPORAN section runs
// for real; only the browser globals it touches are stubbed.
const loadBrowserLogic = () => {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const script = /<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/.exec(html)[1];
  const cut = script.indexOf('// ---------- LAPORAN ----------');
  if (cut < 0) throw new Error('LAPORAN marker missing from index.html');

  const noop = () => {};
  const sandbox = {
    window: {},
    document: { getElementById: () => null, querySelectorAll: () => [], addEventListener: noop },
    sessionStorage: { getItem: () => null, setItem: noop, removeItem: noop },
    localStorage: { getItem: () => null, setItem: noop, removeItem: noop },
    setTimeout, setInterval: noop, clearInterval: noop, console, fetch: noop,
    AbortSignal: { timeout: noop },
  };
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(`${script.slice(0, cut)}
    globalThis.__api = {
      setDB: (value) => { DB = value; },
      setPeriodeIndex: (value) => { bukuPeriodeIndex = value; },
      setParuhIndex: (value) => { bukuParuhIndex = value; },
      setFilterDept: (value) => { nominatifFilterDept = value; },
      selectNominatif: (ids) => { nominatifSelected = new Set(ids); },
      periodeOptions, periodeInfo, paruhOptions, paruhInfo,
      bukuIsiPeriode, bukuExportWorkers, profilBuku,
      sortedTransaksi, normalisasiTanggal, tanggalTakTerbaca,
    };`, sandbox);
  return sandbox.__api;
};

// Values built inside the vm context carry that realm's Array/Object prototypes,
// which node:assert treats as unequal to ours. Round-tripping gives the
// assertions plain local values to compare.
const plain = (value) => JSON.parse(JSON.stringify(value));

const KAS_COA = [
  { kode: '1000', nama: 'Kas Kecil (Petty Cash)', kategori: 'Kas' },
  { kode: '1100', nama: 'Kas di Bank', kategori: 'Kas' },
  { kode: '2000', nama: 'Dana Bahan Makanan (Masuk)', kategori: 'Dana Masuk' },
  { kode: '2010', nama: 'Biaya Bahan Makanan', kategori: 'Biaya Bahan Baku' },
  { kode: '2100', nama: 'Dana Operasional (Masuk)', kategori: 'Dana Masuk' },
  { kode: '2110', nama: 'Biaya Operasional', kategori: 'Biaya Operasional' },
  { kode: '2150', nama: 'Dana Insentif Fasilitas (Masuk)', kategori: 'Dana Masuk' },
  { kode: '2160', nama: 'Biaya Insentif Fasilitas / Upah', kategori: 'Biaya Fasilitas' },
  { kode: '2170', nama: 'PPN', kategori: 'Pajak' },
  { kode: '2180', nama: 'PPh 21/22/23', kategori: 'Pajak' },
];

const baseDB = (overrides = {}) => ({
  setup: {
    namaSPPG: 'SPPG Melati', idSPPG: 'SPPG-0142', alamat: 'Jl. Merdeka 10',
    approvalThreshold: 500000, periodeMulai: '', periodeSelesai: '',
  },
  coa: KAS_COA.map((c) => ({ ...c })),
  pemasok: [], pembelian: [], approvals: [], batch: [], nominatif: [],
  anggaran: { periode: 'Agustus 2026', mulai: '2026-08-01', selesai: '2026-08-31', bahanMakanan: 0, operasional: 0, insentifFasilitas: 0 },
  transaksi: [],
  ...overrides,
});

const trx = (over) => ({
  id: Math.random().toString(36).slice(2), tanggal: '2026-08-02', noBukti: 'B-1', uraian: 'Transaksi',
  akunKas: '1100', akunLawan: '2010', tipe: 'K', jumlah: 100000, approvalStatus: 'approved', ...over,
});

const worker = (over) => ({
  id: 'w-' + Math.random().toString(36).slice(2), nama: 'Personel', pekerjaan: 'Pemorsian',
  hari: 10, tarif: 100000, bpjs: 68000, honorPJ: 0, departemen: 'Dapur', ...over,
});

const ledgerRow = (over) => ({
  tanggal: '2026-08-02', noBukti: 'B-1', uraian: 'Transaksi', debet: 0, kredit: 100000, ...over,
});

// A payload shaped exactly like the one index.html posts.
const bukuPayload = (over = {}) => ({
  filename: 'Buku_Otomatis_Bulanan.xlsx',
  periodeLabel: 'Agustus 2026',
  periodeText: 'Periode : 01 Agu 2026 s.d. 31 Agu 2026',
  dayCount: 31,
  profil: { namaSPPG: 'SPPG Melati', idSPPG: 'SPPG-0142', alamat: 'Jl. Merdeka 10' },
  workers: [worker({ nama: 'Siti Aminah' }), worker({ nama: 'Budi Santoso', pekerjaan: 'Distribusi', tarif: 50000, honorPJ: 50000 })],
  buku: {
    bku: { saldoAwal: 1500000, rows: [ledgerRow({ tanggal: '2026-08-01', debet: 25000000, kredit: 0 }), ledgerRow()] },
    kas: [
      { nama: 'Kas di Bank', jenis: 'bank', saldoAwal: 1500000, rows: [ledgerRow()] },
      { nama: 'Kas Kecil (Petty Cash)', jenis: 'petty', saldoAwal: 0, rows: [] },
    ],
    belanja: [
      { key: 'bahan', jenis: 'Bahan Baku', rows: [{ tanggal: '2026-08-02', noBukti: 'B-1', uraian: 'Sayur', jumlah: 100000, keterangan: '', sumber: 'Kas di Bank' }] },
      { key: 'operasional', jenis: 'Operasional', rows: [] },
      { key: 'fasilitas', jenis: 'Insentif Fasilitas', rows: [] },
    ],
    pajak: [{ jenis: 'PPN', saldoAwal: 0, rows: [ledgerRow({ uraian: 'PPN', kredit: 11000 })] }],
    catatan: {
      ringkasan: { sisaLalu: 1500000, diterima: 25000000, bahanBaku: 100000, operasional: 0, fasilitas: 0 },
      rows: [{ tanggal: '2026-08-01', jumlah: 0 }, { tanggal: '2026-08-02', jumlah: 100000 }],
    },
  },
  ...over,
});

module.exports = {
  ROOT, callHandler, readGenerated, cellValue, loadBrowserLogic, plain,
  baseDB, trx, worker, ledgerRow, bukuPayload,
};
